# Generated by Django 2.2.6 on 2019-10-31 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 12, 23, 49, 76882), verbose_name='date published'),
        ),
    ]
