# Generated by Django 2.2.6 on 2019-10-31 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191031_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 16, 1, 23, 647839), verbose_name='date published'),
        ),
    ]
