# Generated by Django 2.2.6 on 2019-10-31 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191031_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 16, 22, 38, 450242), verbose_name='date published'),
        ),
    ]
