# Generated by Django 2.2.6 on 2019-11-01 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191031_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 15, 41, 33, 701515), verbose_name='date published'),
        ),
    ]
