# Generated by Django 2.2.7 on 2019-12-02 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191101_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=30)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime(2019, 12, 2, 11, 14, 22, 984967), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 11, 14, 22, 983970), verbose_name='date published'),
        ),
    ]
