# Generated by Django 2.2.7 on 2019-12-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191202_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 11, 15, 12, 838751), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 11, 15, 12, 837750), verbose_name='date published'),
        ),
    ]
