# Generated by Django 2.2.7 on 2019-12-02 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191202_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 9, 48, 643428), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 9, 48, 643428), verbose_name='date published'),
        ),
    ]
