# Generated by Django 2.2.7 on 2019-12-03 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191202_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField()),
                ('date', models.DateField()),
                ('club', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 7, 52, 24, 216921), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 7, 52, 24, 216921), verbose_name='date published'),
        ),
    ]
