# Generated by Django 2.2.7 on 2019-12-03 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191203_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
                ('openSeason', models.DateField()),
                ('closeSeason', models.DateField()),
                ('requestor', models.CharField(max_length=15)),
                ('club1', models.CharField(max_length=30)),
                ('club2', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DateRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField()),
                ('date', models.DateField()),
                ('club', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Pairings',
        ),
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 7, 56, 40, 875160), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 7, 56, 40, 875160), verbose_name='date published'),
        ),
    ]
