# Generated by Django 2.2.6 on 2019-12-11 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191211_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sport', models.TextField()),
            ],
            managers=[
                ('leagues', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.League')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 12, 14, 37, 111975), verbose_name='date published'),
        ),
    ]
