# Generated by Django 2.2.6 on 2019-12-11 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191211_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
            managers=[
                ('periods', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
            ],
            managers=[
                ('runs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('teams', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='premierteams',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 12, 43, 49, 213542), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='main.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='main.Team')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Run')),
            ],
        ),
    ]
