# Generated by Django 2.2.6 on 2019-12-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20191211_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_line_item',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Schedule'),
            preserve_default=False,
        ),
    ]
