# Generated by Django 2.2.6 on 2019-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_schedule_line_item_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
