# Generated by Django 2.2.6 on 2019-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_run_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
